spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hospitalDemo
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect




logging:
  level:
    org.springframework: INFO  # Set Spring Framework logging level to INFO
    com.democontroller.controller: DEBUG  # Set your application's logging level to DEBUG